### ISSUE TITLE
Ingest generalization (tracking)

### ISSUE THREAD

**Issue by cawarren** [Recidiviz/recidiviz-data#90]
This issue tracks progress on generalization of the ingest (scraping) pipeline. 

List is roughly ordered, with more self-contained and dependency tasks towards the top, and more complex and dependent work towards the bottom.

Work:
- [x] Migrate region subclass fields to superclasses: issue #63 
- [x] Rename top-level 'scraper' package to 'ingest': issue #82
- [x] Update region_manifest with new config info : issue #84
- [x] Refactor scraper setup() call to be us_ny specific, not general scraper interface : issue #85
- [x] Pull out docket as class, add helper methods : issue #86
- [x] Pull out scraper as a class all scrapers inherit from : issue #87
- [x] Improve session management, rename queue_control : issue #83
- [ ] Add metrics: issue #59 
- [x] Clean up ingest test coverage : issue #89

Moved out of scope:
- Create queue manager : issue #88 (it was determined that sticking with a single queue for each scraping region was better for now until we were sure that the complexity was a) needed, b) in this particular architecture)

**Comment by jessex** [comment]
The spirit of this is complete and the outstanding task, #59, is part of a larger ingest productionalization movement. Closing this now!
